# Spring Config, Persistance, Database
spring:
  application:
    name: service-member
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_member?serverTimezone=Asia/Jakarta&useLegacyDatetimeCode=false
    username: ucommerce
    password: 123qwe
  jpa: 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

# Data Access Object
mybatis:
  mapper-locations: classpath*:/query/sql-*.xml
  type-aliases-package: com.commerce.service.member.dto

